# KNN Pada Data Iris

In [15]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsRegressor 
from sklearn.preprocessing import LabelEncoder

In [22]:
df = pd.read_csv('https://gist.githubusercontent.com/Rezayoga1383/95334cb5c9dfcd55554c625f109dc3c4/raw/d69c0315ae284e70304f735d218c4ec494ef960b/datairis.csv')
baris = df.shape[0]
df.head(baris)

     sepal_length sepal_width  petal_length  petal_width    species
0             5.1         NaN           1.4          0.2     setosa
1             4.9         NaN           1.4          0.2     setosa
2             4.7           ?           1.3          0.2     setosa
3             4.6         3.1           1.5          0.2     setosa
4             5.0         3.6           1.4          0.2     setosa
..            ...         ...           ...          ...        ...
145           6.7           3           5.2          2.3  virginica
146           6.3         2.5           5.0          1.9  virginica
147           6.5           3           5.2          2.0  virginica
148           6.2         3.4           5.4          2.3  virginica
149           5.9           3           5.1          1.8  virginica

[150 rows x 5 columns]

In [23]:
df_copy = df.copy()
df_copy.isnull().sum()

sepal_length    0
sepal_width     2
petal_length    0
petal_width     0
species         0
dtype: int64

In [24]:
df_copy = df_copy.replace('?',np.nan)

In [25]:
df_copy.isnull().sum()

sepal_length    0
sepal_width     3
petal_length    0
petal_width     0
species         0
dtype: int64

In [26]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   147 non-null    object
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(3), object(2)
memory usage: 6.0+ KB

In [27]:
# mengubah fitur sepal_width menjadi tipe data float
df_copy['sepal_width'] = df_copy['sepal_width'].astype(float)

# mengubah fitur species menjadi tipe data int yang awalnya categorical
le = LabelEncoder()
df_copy['species'] = le.fit_transform(df_copy['species'])

In [28]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   147 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [29]:
df_copy = df_copy.fillna(df_copy.mean(numeric_only=True))

In [30]:
df_copy.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [31]:
df_copy.head(baris)

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1      3.05034           1.4          0.2        0
1             4.9      3.05034           1.4          0.2        0
2             4.7      3.05034           1.3          0.2        0
3             4.6      3.10000           1.5          0.2        0
4             5.0      3.60000           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7      3.00000           5.2          2.3        2
146           6.3      2.50000           5.0          1.9        2
147           6.5      3.00000           5.2          2.0        2
148           6.2      3.40000           5.4          2.3        2
149           5.9      3.00000           5.1          1.8        2

[150 rows x 5 columns]

In [32]:
species_column = df_copy['species']
df_copy = df_copy[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].copy()
df_copy = (df_copy - df_copy.min())/(df_copy.max() - df_copy.min())
df_copy['species'] = species_column.copy()
df_copy.head(baris)

     sepal_length  sepal_width  petal_length  petal_width  species
0        0.222222     0.437642      0.067797     0.041667        0
1        0.166667     0.437642      0.067797     0.041667        0
2        0.111111     0.437642      0.050847     0.041667        0
3        0.083333     0.458333      0.084746     0.041667        0
4        0.194444     0.666667      0.067797     0.041667        0
..            ...          ...           ...          ...      ...
145      0.666667     0.416667      0.711864     0.916667        2
146      0.555556     0.208333      0.677966     0.750000        2
147      0.611111     0.416667      0.711864     0.791667        2
148      0.527778     0.583333      0.745763     0.916667        2
149      0.444444     0.416667      0.694915     0.708333        2

[150 rows x 5 columns]

In [33]:
knn = KNeighborsRegressor()

# before we split, make sure you randomize the dataset
np.random.seed(1)
index_shuffled = np.random.permutation(df_copy.index)
shuffled_car_data = df_copy.loc[index_shuffled]

# We will use 75% of the data for training and the remaining 25% for testing
train_index = int(shuffled_car_data.shape[0] * 0.75)
training_data = shuffled_car_data.iloc[0:train_index]
testing_data = shuffled_car_data.iloc[train_index:]

# fit the model with the training data
knn.fit(training_data[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']], training_data['species'])

# predict the species of the testing data
prediction = knn.predict(testing_data[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']])

# calculate the accuracy of the model
accuracy = np.mean(np.abs(prediction - testing_data['species']) <= 0.5)

print(f"Akurasi model KNN: {accuracy:.2%}")

Akurasi model KNN: 92.11%